values = {
    0 : "\\psi",
    1 : "\\beta",
    2 : "\\Gamma",
    3 : "\\gamma",
    4 : "\\Delta",
    5 : "\\delta",
    6 : "\\epsilon",
    7 : "\\varepsilon",
    8 : "\\zeta",
    9 : "\\eta",
    10 : "\\theta",
    11 : "\\lambda", 
    12 : "\\mu", 
    13 : "\\Pi", 
    14 : "\\pi",
    15 : "\\rho",
    16 : "\\Sigma",
    17 : "\\sigma",
    18 : "\\phi",
    19 : "\\varphi",
    20 : "\\Psi",
    21 : "\\omega",
    22 : "+",
    23 : "-",
    24 : "=",
    25 : "\\equiv",
    26 : "\\approx",
    27 : "\\neq",
    28 : "\\pm",
    29 : "\\mp",
    30 : "(",
    31 : ")",
    32 : "\\to",
    33 : "d",
    34 : "D",
    35 : "\\partial",
    36 : "h",
    37 : "\\hbar",
    38 : "\\imath",
    39 : "\\nabla",
    40 : "\\infty",
    41 : "\\sin",
    42 : "\\cos",
    43 : "\\tan",
    44 : "\\sinh",
    45 : "\\cosh",
    46 : "\\tanh",
    
}

def ValToTex(val):
    return values[val]

